### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by at15** [dyweb/awesome-resources#1]
快速学习
http://learnxinyminutes.com/

php设计模式
https://github.com/domnikl/DesignPatternsPHP

php 之道
http://wulijun.github.io/php-the-right-way/

oschina 上一个人对各种php资源的总结，非常全额
http://my.oschina.net/u/1792865/blog/364607

**Comment by at15** [comment]
@swaylq @arrowrowe

**Comment by arrowrowe** [comment]
got

**Comment by at15** [comment]
now moved to weekly
